# Generated by Django 2.2.17 on 2021-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('carnum', models.CharField(max_length=32, unique=True, verbose_name='车牌号')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('level', models.IntegerField(verbose_name='会员套餐')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
    ]
