# Generated by Django 2.2.17 on 2021-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号')),
                ('carport', models.IntegerField(verbose_name='车位')),
                ('begintime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('genre', models.IntegerField(null=True, verbose_name='种类')),
            ],
        ),
        migrations.CreateModel(
            name='Car_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('genre', models.IntegerField(verbose_name='种类')),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
        ),
        migrations.CreateModel(
            name='License_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='car_imgs')),
                ('is_inside', models.BooleanField(default=False)),
            ],
        ),
    ]
