# Generated by Django 2.2.17 on 2021-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210418_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_plate',
            name='car_num',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号'),
        ),
    ]
