# Generated by Django 2.2.17 on 2021-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_license_plate_car_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateTimeField(null=True)),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
        ),
    ]
