# Generated by Django 2.2.17 on 2021-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_in_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('begintime', models.DateTimeField()),
                ('carport', models.IntegerField(verbose_name='车位')),
            ],
        ),
        migrations.CreateModel(
            name='Car_out_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('endtime', models.DateTimeField()),
                ('carport', models.IntegerField(verbose_name='车位')),
            ],
        ),
    ]
