# Generated by Django 2.2.17 on 2021-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_car_in_record_car_out_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('is_valid', models.BooleanField(default=False)),
                ('vip_begintime', models.DateTimeField()),
                ('vip_deadline', models.DateTimeField()),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
        ),
    ]
