# Generated by Django 2.2.17 on 2021-05-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_extra_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_charge',
            name='is_valid',
        ),
    ]
