# Generated by Django 2.2.17 on 2021-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_extra_charge_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_charge',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
